# Basics of Regression
#### 
This is a basic Tutorial of Regression for predictive analysis:

Regression
1. Linear regression

### Import Libraries and Packages
`Scikit Learn` is a package having useful libraries for regression analysis
1. For Linear Regression we import `LinearRegression` function


In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

### Data

We will work with a simple understandable data

In [94]:
# Two lists x and y

x= [2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40]
y = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]


Convert the list into arrays

In [95]:
x = np.array(x)
y = np.array(y)

Check for the data by printing x and y

In [96]:
print(x)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [97]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


For linear Regression we need the dependent variable into tabular for so we reshapr the array to column arrary

In [98]:
x = x.reshape(-1, 1)
print(x)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]]


### Training Model

In [99]:
model = LinearRegression()

In [100]:
model.fit(x,y)

LinearRegression()

### Evaluate the model

Find coefficient of determination, intercept and slope

In [101]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)

coefficient of determination: 1.0
intercept: 0.0
slope: [0.5]


* `r^2 score` determines the accuracy of model. Higher the r^2 value higher will be the accuracy of model. `Range of r^2 is 0 to 1`.

* `Intercept` or `y-intercept` is the point at which the line meet with y-axis. In the line formula y = mx + c, c is intercept.

* `slope` or `gradient` tells us how steep the line is.

### Prediction

first we check for the actual values of x

In [102]:
y_pred = model.predict(x)

print(f"Predicted values for x:\n{y_pred}")
print(f"Actual values for y:\n{y}")

Predicted values for x:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
Actual values for y:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Now give the model some other values to predict the y of that numeber (50, ?) and  (61, ?)

In [103]:
z = [50,61]
z = np.array(z)
z = z.reshape(-1,1)

In [104]:
y_pred = model.predict(z)

print(f"Predicted values:\n{y_pred}")

Predicted values:
[25.  30.5]


it gives 100 accurate values as all the y values in our initial list is half of the respective x values.

This is a very basics to understand how the regression model work. see you with some complex data and modeling